//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int Item_ID { get; set; }
        public Nullable<int> Item_Grp_ID { get; set; }
        public Nullable<int> BarCode { get; set; }
        public string Item_Name { get; set; }
        public string Item_Name_AR { get; set; }
        public int Unit_ID { get; set; }
        public Nullable<int> Qunt { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public Nullable<double> PriceForOnce { get; set; }
        public Nullable<double> Price_dozen { get; set; }
        public Nullable<int> Min_Limit { get; set; }
        public Nullable<int> Max_Limit { get; set; }
        public Nullable<System.DateTime> Exp_Date { get; set; }
        public Nullable<int> Comp_ID { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public Nullable<int> City_ID { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string Entered_By { get; set; }
        public Nullable<int> Warehouse_ID { get; set; }
    
        public virtual City City { get; set; }
        public virtual Company Company { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual Items_Group Items_Group { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
