//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tree
    {
        public int Acc_No { get; set; }
        public int GL_ID { get; set; }
        public int Aux_ID { get; set; }
        public string Acc_Name { get; set; }
        public string Acc_Name_AR { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string Entered_By { get; set; }
    
        public virtual Auxiliary Auxiliary { get; set; }
        public virtual GL GL { get; set; }
    }
}
